### ISSUE TITLE
Consider using unarchive module rather than running unzip

### ISSUE THREAD

**Issue by lmilbaum** [shelleg/ansible-role-gradle#1]
TASK [shelleg.gradle : Extract Gradle] *****************************************
changed: [ec2-52-214-101-23.eu-west-1.compute.amazonaws.com]
 [WARNING]: Consider using unarchive module rather than running unzip

**Comment by hagzag** [comment]
@lioramilbaum v1.0.0 has released with a few fixes a few minutes ago.

**Comment by lmilbaum** [comment]
works perfectly. Thx for the quick fix. I am using gradle 3.5.
