### ISSUE TITLE
symlink to always refers to latest

### ISSUE THREAD

**Issue by 030** [shelleg/ansible-role-gradle#5]
At the moment gradle is installed in

```
/usr/local/share/gradle-3.3/
```

if a symlink would be created

```
/usr/local/share/gradle-latest
```

then apps, e.g. ide's do not have to be changed if gradle is updated

**Comment by hagzag** [comment]
I'll do my best to take a look tomorrow. I'm at a conference ATM

**Comment by 030** [comment]
invalid
